name: Discord Bot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Укажите версию, на которой пишете

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          pip install flake8
          # Остановит сборку, если есть синтаксические ошибки или неопределенные имена
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Предупреждения (стиль кода) не роняют сборку
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        run: |
          # Если у вас есть тесты (pytest), раскомментируйте строку ниже
          # pytest
          echo "No tests specified, skipping..."
